name: Update README

on:
  pull_request:
    types: [closed]
    paths:
      - 'content/profiles/**'
      - 'static/images/**'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update README
      run: python .github/scripts/update_readme.py
