name: Update README

on:
  pull_request:
    types: [closed]
    paths:
      - 'content/profiles/**'
      - 'static/images/**'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.x'
    - name: Install pip3
      run: python3 -m pip3 install --upgrade pip setuptools wheel
      
    - name: Install dependencies
      run: python3 -m pip3 install Pillow

    - name: Update README
      run: python3 .github/scripts/update_readme.py
